apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-go-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - go-micro.johnmichaelgeorge.com
        - broker.johnmichaelgeorge.com
      secretName: tls-secret-2
  rules:
    - host: go-micro.johnmichaelgeorge.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end
                port:
                  number: 8081
    - host: broker.johnmichaelgeorge.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: broker-service
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-website-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - johnmichaelgeorge.com
      secretName: tls-website
  rules:
    - host: johnmichaelgeorge.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80
